@baseUrl = http://127.0.0.1:8080 
@firebaseToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImEyZGZiOGEzOGI1MmQ5ZjA5ZWRjYWE1MDcwYTBlOGYwYTllMDk4YmEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc2Mtc291bmRzaWdodCIsImF1ZCI6InNjLXNvdW5kc2lnaHQiLCJhdXRoX3RpbWUiOjE3NzMzNTU3MjQsInVzZXJfaWQiOiJ1U1BjQnZpUGtxUURPdUU3RDQ4cVM1MnRkMU0yIiwic3ViIjoidVNQY0J2aVBrcVFET3VFN0Q0OHFTNTJ0ZDFNMiIsImlhdCI6MTc3MzM1NTcyNCwiZXhwIjoxNzczMzU5MzI0LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.gu0rjlC1CXuhHjpaXCgsvmXrWMV61nqK2sT8k4jttAV54lShJLiImBhyGT-BaI62AhaWDrDIY66oSs2onPVOWFiOc652K4QI3LEnmi1vGAyq-TLYK2eMmiT4_Drz2J_UeiHQxv1cP-xrU4fBze0b42hwT5j86k78IKI1DksiOuZw6iGk23eaFW3YU_3QkfawA7Zq9YFACYnXjws1v4rcTNkBWuPutjJi2OrG-aT1LJm8DHg69p6sRqU289EHFNuRKBKZ8DRt2UeYPx4-N2gm0qQ3VaQ9LqpY9dpr04i2e4dJ0SqA8gVUgwR-OY1HAcfIsyn05I53DZ3hEprWjpazmA
@jobId = d875d20b87d4451fa644e70e965358a6

### Firebase Auth check 
GET {{baseUrl}}/api/me
Authorization: Bearer {{firebaseToken}}

### 작업 시작
POST {{baseUrl}}/api/analyze
Content-Type: application/json
Authorization: Bearer {{firebaseToken}}

{
  "youtube_url": "https://www.youtube.com/watch?v=gIHjXDxghqE",
  "title": "Interstellar Test"
}

### 상태 조회
GET {{baseUrl}}/api/status?job_id={{jobId}}
Authorization: Bearer {{firebaseToken}}

### 결과 조회
GET {{baseUrl}}/api/result?job_id={{jobId}}
Authorization: Bearer {{firebaseToken}}