@baseUrl = http://127.0.0.1:8080 
@firebaseToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc2Mtc291bmRzaWdodCIsImF1ZCI6InNjLXNvdW5kc2lnaHQiLCJhdXRoX3RpbWUiOjE3NzMxOTUyMTksInVzZXJfaWQiOiJ1U1BjQnZpUGtxUURPdUU3RDQ4cVM1MnRkMU0yIiwic3ViIjoidVNQY0J2aVBrcVFET3VFN0Q0OHFTNTJ0ZDFNMiIsImlhdCI6MTc3MzE5NTIxOSwiZXhwIjoxNzczMTk4ODE5LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.UGEAuLCegMDsYDr2BDaONvB2aT-7WyYTdDmoITk60YfcC63xjPbLwUL_P0W5h_uPEu5YQSQ1y6ZBLV7KT5zyYdzvCQ0RrifScaJFqEHpSVkEc7vFD88rztpyKeXHbHdkKZ7kwVyuUDH7UGUF-5Nlq8QvKn9ySGQ1YhC9lmdUrODuoFaDLJALzV-HtJtonQWEl2DklyGqCzhkT9hi68u1lYhFVnoyiw_L9o-rQDGemtmKpYWmsde2_F_s-E-E5bQw-m7oVCtEHECd0iONgJosjliuX-EN1CYl2KSOUeHzJGz6IG9SdNvGbyRTCqcyjCfPZFN_mL-LalUqGr6BH1cSYQ
@jobId = d455318fa6ca4a8aab20e467fd507be9

### Firebase Auth check 
GET {{baseUrl}}/api/me
Authorization: Bearer {{firebaseToken}}

### 작업 시작
POST {{baseUrl}}/api/analyze
Content-Type: application/json
Authorization: Bearer {{firebaseToken}}

{
  "youtube_url": "https://www.youtube.com/watch?v=gIHjXDxghqE",
  "title": "Interstellar Test"
}

### 상태 조회
GET {{baseUrl}}/api/status?job_id={{jobId}}
Authorization: Bearer {{firebaseToken}}

### 결과 조회
GET {{baseUrl}}/api/result?job_id={{jobId}}
Authorization: Bearer {{firebaseToken}}